### ISSUE TITLE
Using spring-cloud-starter-parent 1.0.1 or 1.0.2 fails

### ISSUE THREAD

**Issue by HagarJNode** [spring-cloud-samples/svn-config-server#2]
Hi there,
Updating the spring-cloud-starter-parent from 1.0.0 to 1.0.1 or 1.0.2 make the example stop working. Am I the only one who see this problem? It looks like there are no connection to the data in svn.

**Comment by thiagolocatelli** [comment]
@HagarJNode  were you able to make the client application work without the default placeholder "World" in the @Value annotation?

**Comment by HagarJNode** [comment]
I've just tested it without the default value in the @Value annotation and it's working as it should. Btw I did worked my way around the parent problem by removing the parent part and adding the following:

``` xml
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-config-server</artifactId>
      <version>1.0.3.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.tmatesoft.svnkit</groupId>
      <artifactId>svnkit</artifactId>
      <version>1.8.7</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>1.3.0.RELEASE</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

**Comment by spencergibb** [comment]
It was missing a new starter, `spring-cloud-starter-config`.
See the [Angel.x branch](https://github.com/spring-cloud-samples/svn-config-server/tree/Angel.x) for howto do it with Angel.SR4, master for Brixton.
